### PR TITLE
Fixes: Padding for both end is not same #9

### LINKED ISSUE #9: Padding for both end is not same
https://devuiv2.vercel.app/templates/chat

image
image

### PR DESCRIPTION
**Pull request by musiur**
Fixes #9
- Create Personal Chat > select user > padding issue at px
- Create Group Chat > select user > padding issue at px

### CODE REVIEW

File: src/components/templates/chat/create-group-chat.jsx [hunk 1]
```diff
@@ -84,16 +84,18 @@ const CreateGroupChat = () => {
...
-                    placeholder="Select a user..."
-                    autoComplete="false"
-                    className="w-full border-[1px] border-white bg-black p-4 text-white placeholder:text-gray-500"
-                  >
-                    <option value="0">John Doe</option>
-                    <option value="1">Jane Doe</option>
-                    <option value="2">Mark Smith</option>
-                    <option value="3">Tiger Woods</option>
-                  </select>
+                  <div className="w-full border-[1px] border-white px-4">
```
Comment (wajeshubham) [inline src/components/templates/chat/create-group-chat.jsx]: Only giving padding at the right side makes sense in my opinion. Giving left side padding to the select pushes selected option text to the right, creating inconsistency. Please replace `px-4` to `pr-4`

Comment (musiur) [reply src/components/templates/chat/create-group-chat.jsx]: I think this is now ok! 😅 

image

Comment (musiur) [reply src/components/templates/chat/create-group-chat.jsx]: I have resolved it and made **pr-4 to the outer div** and made **checkbox pl-4** (so that text get a little breath with pl-4)
